import {database} from '../../../lib/db';
import {empty} from '../../../lib/ledger';
import {z} from 'zod';
import {safeImageUrl} from '../../../lib/card-images';
const id=z.string().min(1).max(80),str=z.string().max(500),day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!Number.isNaN(Date.parse(s))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s),optionalDay=z.union([day,z.literal('')]);
const name=z.string().trim().min(1).max(500);
const schema=z.object({revision:z.number().int().nonnegative(),data:z.object({cards:z.array(z.object({id,name,bank:str,closeDay:z.number().int().min(1).max(31),color:z.string().regex(/^#[0-9a-fA-F]{6}$/),imageZoom:z.number().min(1).max(2).optional(),lookupOnly:z.boolean().optional(),imageUrl:z.string().max(2000).refine(v=>v===''||safeImageUrl(v)).optional()})).max(100),campaigns:z.array(z.object({id,cardId:id,name,kind:z.enum(['reward','spend','unlimited']),period:z.enum(['month','bill','quarter','custom']),target:z.number().nonnegative().max(1e10),rate:z.number().min(0).max(100),rateLabel:z.string().trim().max(80).optional(),start:optionalDay,end:optionalDay,notes:str,channels:z.array(z.string().trim().min(1).max(80)).max(100).optional()})).max(500),entries:z.array(z.object({id,cardId:id,date:day,amount:z.number().positive().max(1e10),note:str,campaignIds:z.array(id).max(500),reward:z.number().min(0).max(1e10).nullable()})).max(10000)})});
export const dynamic='force-dynamic';
export async function GET(){try{const sql=database();const rows=await sql`SELECT payload,revision,updated_at FROM ledgers WHERE id = 'shared'`;const row=rows[0];return Response.json(row?{data:row.payload,revision:row.revision,updatedAt:row.updated_at}:{data:empty,revision:0,updatedAt:null},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'雲端資料暫時無法讀取，請重試。'},{status:503});}}
export async function PUT(request:Request){if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'來源不符'},{status:403});try{const body=await request.text();if(new TextEncoder().encode(body).byteLength>3000000)return Response.json({error:'資料超過容量限制'},{status:413});let input:unknown;try{input=JSON.parse(body);}catch{return Response.json({error:'資料格式無效，請重新確認。'},{status:400});}const parsed=schema.safeParse(input);if(!parsed.success)return Response.json({error:'請檢查欄位與日期'},{status:400});const {data,revision}=parsed.data; const cardIds=new Set(data.cards.map(c=>c.id)),campaignById=new Map(data.campaigns.map(c=>[c.id,c]));if(cardIds.size!==data.cards.length||campaignById.size!==data.campaigns.length||new Set(data.entries.map(e=>e.id)).size!==data.entries.length||data.campaigns.some(c=>!cardIds.has(c.cardId)||(c.start&&c.end&&c.start>c.end)||(c.kind!=='unlimited'&&(c.target<=0||(c.period==='custom'&&(!c.start||!c.end)))))||data.entries.some(e=>!cardIds.has(e.cardId)||new Set(e.campaignIds).size!==e.campaignIds.length||e.campaignIds.some(cid=>campaignById.get(cid)?.cardId!==e.cardId)))return Response.json({error:'卡片、活動或日期設定無效'},{status:400});
 const sql=database();const results=await sql.transaction([sql`INSERT INTO ledgers (id,payload,revision) VALUES ('shared',${JSON.stringify(empty)}::jsonb,0) ON CONFLICT (id) DO NOTHING`,sql`UPDATE ledgers SET payload = ${JSON.stringify(data)}::jsonb, revision = revision + 1, updated_at = now() WHERE id = 'shared' AND revision = ${revision} RETURNING revision,updated_at`]);const row=results[1][0];if(!row)return Response.json({error:'帳簿已有其他人更新。請同步最新資料後再儲存。'},{status:409});return Response.json({revision:row.revision,updatedAt:row.updated_at});}catch(e){console.error(e);return Response.json({error:'儲存失敗，輸入仍保留，請重試。'},{status:503});}}
